#Create a file application-local.properties and fills the below keys and paste it into the file.

spring.datasource.url=your_db_url
spring.datasource.username=your_db_username
spring.datasource.password=your_db_password

# ── Google OAuth2 ─────────────────────────────────────────────────────────────

spring.security.oauth2.client.registration.google.client-id=your_google_client_id
spring.security.oauth2.client.registration.google.client-secret=your_google_client_secret
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# ── JWT ───────────────────────────────────────────────────────────────────────

app.jwt.secret=your_jwt_secret
app.jwt.expiration-ms=your_jwt_expiration_ms

# ── Frontend URL ───────────────────────────────────────────────────────────────

app.frontend-url=http://localhost:3000